/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    TinyAlert: typeof import('@opentiny/vue')['Alert']
    TinyAnchor: typeof import('@opentiny/vue')['Anchor']
    TinyButton: typeof import('@opentiny/vue')['Button']
    TinyCascader: typeof import('@opentiny/vue')['Cascader']
    TinyCheckbox: typeof import('@opentiny/vue')['Checkbox']
    TinyCheckboxButton: typeof import('@opentiny/vue')['CheckboxButton']
    TinyCheckboxGroup: typeof import('@opentiny/vue')['CheckboxGroup']
    TinyCol: typeof import('@opentiny/vue')['Col']
    TinyDatePicker: typeof import('@opentiny/vue')['DatePicker']
    TinyDialogBox: typeof import('@opentiny/vue')['DialogBox']
    TinyForm: typeof import('@opentiny/vue')['Form']
    TinyFormItem: typeof import('@opentiny/vue')['FormItem']
    TinyGrid: typeof import('@opentiny/vue')['Grid']
    TinyGridColumn: typeof import('@opentiny/vue')['GridColumn']
    TinyInput: typeof import('@opentiny/vue')['Input']
    TinyLayout: typeof import('@opentiny/vue')['Layout']
    TinyNumeric: typeof import('@opentiny/vue')['Numeric']
    TinyOption: typeof import('@opentiny/vue')['Option']
    TinyPager: typeof import('@opentiny/vue')['Pager']
    TinyRadioGroup: typeof import('@opentiny/vue')['RadioGroup']
    TinyRate: typeof import('@opentiny/vue')['Rate']
    TinyRow: typeof import('@opentiny/vue')['Row']
    TinySelect: typeof import('@opentiny/vue')['Select']
    TinySlider: typeof import('@opentiny/vue')['Slider']
    TinySwitch: typeof import('@opentiny/vue')['Switch']
    TinyTimeLine: typeof import('@opentiny/vue')['TimeLine']
    TinyTree: typeof import('@opentiny/vue')['Tree']
  }
}
